spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/binding?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yellowzerow@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/